version: '3'

services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  mysql:
    container_name: flask_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - mynetwork
    ports:
      - '3306:3306'

  db_gateway:
    container_name: db_gateway
    build:
      context: ./db_gateway
    environment:
      DB_HOST: mysql
      DB_NAME: db
      DB_USER: user
      DB_PASSWORD: password
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    networks:
      - mynetwork

networks:
  mynetwork:
